apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab00
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/jreb-123/devops-lab00.git'
    targetRevision: main
    path: charts/app
    helm:
      valueFiles:
        - values.yaml   # aseg√∫rate que este archivo tenga service.port definido
      parameters:
        - name: image.repository
          value: jrebterraformacr.azurecr.io/lab00
        - name: image.tag
          value: latest
      skipTests: true   # evita que Helm ejecute templates de tests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
